// Lead type definition
export type Lead = {
  id: number
  name: string
  userType: string
  property: string
  stage: string
  assignedTo: string
  phone: string
  email: string
  secondaryPhone?: string
  secondaryEmail?: string
  createdAt: string
  unitDetails: string
  numberOfUnits: number
  lastCallStatus: string
  nextFollowUp: string
  ownerType?: string // Owner type 1, 2, 3, or 4
  prospectType?: string // Prospect type 1, 2, 3, or 4
  completedSteps?: number // Number representing which step is completed (1-4)
  category?: string // Category for owner leads
  emailsSent?: number // Number of emails sent
  deals?: number // Number of deals
  nextAction?: string // Next action to take
  source?: string // Lead source
  lastTouch?: string // Last touch date
  interestedUnits?: { address: string; unit: string }[] // Unit addresses for lease prospects
}

export const ownerType1Stages = [
  "New lead",
  "Attempting to contact",
  "Scheduled Intro call",
  "Working",
  "Closing",
  "New client",
]

export const ownerType2Stages = [
  "Initial Contact",
  "Qualification",
  "Property Assessment",
  "Proposal Sent",
  "Negotiation",
  "Agreement Signed",
]

export const ownerType3Stages = [
  "Inquiry Received",
  "Documentation Review",
  "Site Visit Scheduled",
  "Due Diligence",
  "Contract Phase",
  "Onboarded",
]

export const ownerType4Stages = [
  "Lead Generation",
  "First Meeting",
  "Needs Analysis",
  "Solution Presentation",
  "Final Review",
  "Client Active",
]

export const ownerStages = ownerType1Stages

// Tenant stages
export const tenantStages = [
  "New Prospects",
  "Appointment Booked with LC",
  "Scheduled Showing",
  "No Show – Prospect",
  "Showing Agent – No Show",
  "Showing Completed – Awaiting Feedback",
  "Not Interested / Disliked Property",
  "Interested – Application Sent",
  "Application Received – Under Review",
  "Application Rejected",
  "Application Approved – Lease Sent",
  "Lease Signed – Schedule Move In",
  "Move In – Completed and Feedback",
  "Tenant – Lost or Backed Out",
]

export const prospectType1Stages = [
  "New Prospects",
  "Appointment Booked with LC",
  "Scheduled Showing",
  "No Show – Prospect",
  "Showing Agent – No Show",
  "Showing Completed – Awaiting Feedback",
  "Not Interested / Disliked Property",
  "Interested – Application Sent",
  "Application Received – Under Review",
  "Application Rejected",
  "Application Approved – Lease Sent",
  "Lease Signed – Schedule Move In",
  "Move In – Completed and Feedback",
  "Tenant – Lost or Backed Out",
]

export const prospectType2Stages = [
  "Initial Inquiry",
  "Qualifying Call Scheduled",
  "Property Tour Booked",
  "Tour Completed",
  "Application Submitted",
  "Application Processing",
  "Approved – Lease Ready",
]

export const prospectType3Stages = [
  "Lead Received",
  "First Contact Made",
  "Showing Requested",
  "Showing Confirmed",
  "Post-Showing Follow-up",
  "Offer Submitted",
  "Lease Negotiation",
]

export const prospectType4Stages = [
  "Prospect Contacted",
  "Interest Confirmed",
  "Viewing Scheduled",
  "Viewing Complete",
  "Decision Pending",
  "Lease Documents Sent",
  "Move-in Scheduled",
]

export const initialLeadsData: Lead[] = [
  // ==========================================
  // OWNER LEADS - New lead (10 records)
  // ==========================================
  {
    id: 1,
    name: "Emma Wilson",
    userType: "Owner",
    property: "14 Oak Ave",
    stage: "New lead",
    assignedTo: "Raj",
    phone: "+1 (555) 606-0606",
    email: "emma.wilson@example.com",
    createdAt: "11/12/2025",
    unitDetails: "Single Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/18/2025",
    ownerType: "type1",
  },
  {
    id: 2,
    name: "Hannah Lee",
    userType: "Owner",
    property: "221 Lakeview",
    stage: "New lead",
    assignedTo: "Nina",
    phone: "+1 (555) 262-6262",
    email: "hannah.lee@example.com",
    createdAt: "11/12/2025",
    unitDetails: "Single Family",
    numberOfUnits: 1,
    lastCallStatus: "No Answer",
    nextFollowUp: "11/19/2025",
    ownerType: "type1",
  },
  {
    id: 3,
    name: "Sarah Lee",
    userType: "Owner",
    property: "500 Maple Dr",
    stage: "New lead",
    assignedTo: "Nina",
    phone: "+1 (555) 202-0202",
    email: "sarah.lee@example.com",
    createdAt: "11/09/2025",
    unitDetails: "Single Family",
    numberOfUnits: 1,
    lastCallStatus: "Cancelled",
    nextFollowUp: "11/25/2025",
    ownerType: "type2",
  },
  {
    id: 4,
    name: "Brian O'Neal",
    userType: "Owner",
    property: "212 Pine St",
    stage: "Attempting to contact",
    assignedTo: "Raj",
    phone: "+1 (555) 141-4141",
    email: "brian.oneal@example.com",
    createdAt: "11/05/2025",
    unitDetails: "Multi Family",
    numberOfUnits: 2,
    lastCallStatus: "Call me Later",
    nextFollowUp: "11/12/2025",
    ownerType: "type1",
  },
  {
    id: 5,
    name: "Marcus Chen",
    userType: "Owner",
    property: "555 Pine St",
    stage: "Initial Contact",
    assignedTo: "Raj",
    phone: "+1 (555) 999-8888",
    email: "marcus.c@example.com",
    createdAt: "11/18/2025",
    unitDetails: "Multi Family",
    numberOfUnits: 12,
    lastCallStatus: "No Answer",
    nextFollowUp: "11/21/2025",
    ownerType: "type2",
  },
  {
    id: 6,
    name: "Victoria Palmer",
    userType: "Owner",
    property: "892 Sunset Blvd",
    stage: "Inquiry Received",
    assignedTo: "Kim",
    phone: "+1 (555) 444-5555",
    email: "victoria.p@example.com",
    createdAt: "11/20/2025",
    unitDetails: "Single Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/24/2025",
    ownerType: "type3",
  },
  {
    id: 7,
    name: "Derek Morrison",
    userType: "Owner",
    property: "45 Willow Creek",
    stage: "Lead Generation",
    assignedTo: "Luis",
    phone: "+1 (555) 666-7777",
    email: "derek.m@example.com",
    createdAt: "11/19/2025",
    unitDetails: "Multi Family",
    numberOfUnits: 4,
    lastCallStatus: "No Answer",
    nextFollowUp: "11/22/2025",
    ownerType: "type4",
  },
  {
    id: 8,
    name: "Linda Foster",
    userType: "Owner",
    property: "128 Birch Lane",
    stage: "Scheduled Intro call",
    assignedTo: "Nora",
    phone: "+1 (555) 888-9999",
    email: "linda.f@example.com",
    createdAt: "11/21/2025",
    unitDetails: "Single Family",
    numberOfUnits: 1,
    lastCallStatus: "Call me Later",
    nextFollowUp: "11/26/2025",
    ownerType: "type1",
  },
  {
    id: 9,
    name: "Robert Chang",
    userType: "Owner",
    property: "777 Harbor View",
    stage: "Qualification",
    assignedTo: "Nina",
    phone: "+1 (555) 111-2222",
    email: "robert.c@example.com",
    createdAt: "11/22/2025",
    unitDetails: "Apartment",
    numberOfUnits: 8,
    lastCallStatus: "Connected",
    nextFollowUp: "11/25/2025",
    ownerType: "type2",
  },
  {
    id: 10,
    name: "Amanda Torres",
    userType: "Owner",
    property: "350 Ridge Road",
    stage: "Documentation Review",
    assignedTo: "Raj",
    phone: "+1 (555) 333-4444",
    email: "amanda.t@example.com",
    createdAt: "11/23/2025",
    unitDetails: "Multi Family",
    numberOfUnits: 3,
    lastCallStatus: "No Answer",
    nextFollowUp: "11/27/2025",
    ownerType: "type3",
  },

  // ==========================================
  // OWNER LEADS - Attempting to contact (10 records)
  // ==========================================
  {
    id: 11,
    name: "Grace Liu",
    userType: "Owner",
    property: "654 Spruce Dr",
    stage: "Attempting to contact",
    assignedTo: "Kim",
    phone: "+1 (555) 191-9191",
    email: "grace.liu@example.com",
    createdAt: "10/18/2025",
    unitDetails: "Multi Family",
    numberOfUnits: 3,
    lastCallStatus: "No Answer",
    nextFollowUp: "10/22/2025",
    ownerType: "type1",
  },
  {
    id: 12,
    name: "Nora Svensson",
    userType: "Owner",
    property: "3 Harbor Ln",
    stage: "Attempting to contact",
    assignedTo: "Nora",
    phone: "+1 (555) 303-3030",
    email: "nora.s@example.com",
    createdAt: "10/09/2025",
    unitDetails: "Single Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "10/15/2025",
    ownerType: "type1",
  },
  {
    id: 13,
    name: "Elena Rodriguez",
    userType: "Owner",
    property: "777 Oak Ln",
    stage: "Attempting to contact",
    assignedTo: "Nina",
    phone: "+1 (555) 777-6666",
    email: "elena.r@example.com",
    createdAt: "11/16/2025",
    unitDetails: "Single Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/22/2025",
    ownerType: "type1",
  },
  {
    id: 14,
    name: "James Patterson",
    userType: "Owner",
    property: "92 Cherry Blossom",
    stage: "Attempting to contact",
    assignedTo: "Raj",
    phone: "+1 (555) 454-5454",
    email: "james.p@example.com",
    createdAt: "11/10/2025",
    unitDetails: "Multi Family",
    numberOfUnits: 6,
    lastCallStatus: "No Answer",
    nextFollowUp: "11/15/2025",
    ownerType: "type1",
  },
  {
    id: 15,
    name: "Michelle Wang",
    userType: "Owner",
    property: "188 Elm Street",
    stage: "Attempting to contact",
    assignedTo: "Luis",
    phone: "+1 (555) 565-6565",
    email: "michelle.w@example.com",
    createdAt: "11/08/2025",
    unitDetails: "Apartment",
    numberOfUnits: 12,
    lastCallStatus: "Cancelled",
    nextFollowUp: "11/14/2025",
    ownerType: "type1",
  },
  {
    id: 16,
    name: "Kevin Brooks",
    userType: "Owner",
    property: "420 Maple Heights",
    stage: "Attempting to contact",
    assignedTo: "Kim",
    phone: "+1 (555) 676-7676",
    email: "kevin.b@example.com",
    createdAt: "11/12/2025",
    unitDetails: "Single Family",
    numberOfUnits: 1,
    lastCallStatus: "Call me Later",
    nextFollowUp: "11/18/2025",
    ownerType: "type1",
  },
  {
    id: 17,
    name: "Sandra Miller",
    userType: "Owner",
    property: "55 Oceanview",
    stage: "Attempting to contact",
    assignedTo: "Nora",
    phone: "+1 (555) 787-8787",
    email: "sandra.m@example.com",
    createdAt: "11/14/2025",
    unitDetails: "Multi Family",
    numberOfUnits: 4,
    lastCallStatus: "No Answer",
    nextFollowUp: "11/20/2025",
    ownerType: "type1",
  },
  {
    id: 18,
    name: "Thomas Garcia",
    userType: "Owner",
    property: "300 Valley Road",
    stage: "Attempting to contact",
    assignedTo: "Nina",
    phone: "+1 (555) 898-9898",
    email: "thomas.g@example.com",
    createdAt: "11/15/2025",
    unitDetails: "Single Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/21/2025",
    ownerType: "type1",
  },
  {
    id: 19,
    name: "Jessica Adams",
    userType: "Owner",
    property: "67 Riverside Dr",
    stage: "Attempting to contact",
    assignedTo: "Raj",
    phone: "+1 (555) 909-0909",
    email: "jessica.a@example.com",
    createdAt: "11/17/2025",
    unitDetails: "Apartment",
    numberOfUnits: 2,
    lastCallStatus: "No Answer",
    nextFollowUp: "11/23/2025",
    ownerType: "type1",
  },
  {
    id: 20,
    name: "Daniel Kim",
    userType: "Owner",
    property: "145 Park Avenue",
    stage: "Attempting to contact",
    assignedTo: "Luis",
    phone: "+1 (555) 010-1010",
    email: "daniel.k@example.com",
    createdAt: "11/18/2025",
    unitDetails: "Multi Family",
    numberOfUnits: 8,
    lastCallStatus: "Call me Later",
    nextFollowUp: "11/24/2025",
    ownerType: "type1",
  },

  // ==========================================
  // OWNER LEADS - Scheduled Intro call (10 records)
  // ==========================================
  {
    id: 21,
    name: "Sofia Gomez",
    userType: "Owner",
    property: "445 Sycamore St",
    stage: "Scheduled Intro call",
    assignedTo: "Luis",
    phone: "+1 (555) 131-3142",
    email: "sofia.g@example.com",
    createdAt: "10/24/2025",
    unitDetails: "Multi Family",
    numberOfUnits: 6,
    lastCallStatus: "Connected",
    nextFollowUp: "10/30/2025",
    ownerType: "type1",
  },
  {
    id: 22,
    name: "Priya Das",
    userType: "Owner",
    property: "88 Riverbend",
    stage: "Scheduled Intro call",
    assignedTo: "Nina",
    phone: "+1 (555) 323-3232",
    email: "priya.d@example.com",
    createdAt: "10/05/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "Call me Later",
    nextFollowUp: "10/12/2025",
    ownerType: "type1",
  },
  {
    id: 23,
    name: "William Turner",
    userType: "Owner",
    property: "201 Summit Ave",
    stage: "Scheduled Intro call",
    assignedTo: "Kim",
    phone: "+1 (555) 121-2121",
    email: "william.t@example.com",
    createdAt: "11/05/2025",
    unitDetails: "Single Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/10/2025",
    ownerType: "type1",
  },
  {
    id: 24,
    name: "Natalie Brown",
    userType: "Owner",
    property: "78 Magnolia Ct",
    stage: "Scheduled Intro call",
    assignedTo: "Raj",
    phone: "+1 (555) 232-3232",
    email: "natalie.b@example.com",
    createdAt: "11/07/2025",
    unitDetails: "Multi Family",
    numberOfUnits: 3,
    lastCallStatus: "Connected",
    nextFollowUp: "11/12/2025",
    ownerType: "type1",
  },
  {
    id: 25,
    name: "Christopher Lee",
    userType: "Owner",
    property: "560 Cedar Point",
    stage: "Scheduled Intro call",
    assignedTo: "Nora",
    phone: "+1 (555) 343-4343",
    email: "chris.l@example.com",
    createdAt: "11/09/2025",
    unitDetails: "Apartment",
    numberOfUnits: 20,
    lastCallStatus: "Connected",
    nextFollowUp: "11/14/2025",
    ownerType: "type1",
  },
  {
    id: 26,
    name: "Rachel Green",
    userType: "Owner",
    property: "99 Brookside",
    stage: "Scheduled Intro call",
    assignedTo: "Luis",
    phone: "+1 (555) 454-5454",
    email: "rachel.g@example.com",
    createdAt: "11/11/2025",
    unitDetails: "Single Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/16/2025",
    ownerType: "type1",
  },
  {
    id: 27,
    name: "Andrew Martinez",
    userType: "Owner",
    property: "234 Hillcrest",
    stage: "Scheduled Intro call",
    assignedTo: "Nina",
    phone: "+1 (555) 565-6565",
    email: "andrew.m@example.com",
    createdAt: "11/13/2025",
    unitDetails: "Multi Family",
    numberOfUnits: 5,
    lastCallStatus: "Connected",
    nextFollowUp: "11/18/2025",
    ownerType: "type1",
  },
  {
    id: 28,
    name: "Lisa Thompson",
    userType: "Owner",
    property: "412 Meadow Lane",
    stage: "Scheduled Intro call",
    assignedTo: "Kim",
    phone: "+1 (555) 676-7676",
    email: "lisa.t@example.com",
    createdAt: "11/15/2025",
    unitDetails: "Single Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/20/2025",
    ownerType: "type1",
  },
  {
    id: 29,
    name: "Michael Scott",
    userType: "Owner",
    property: "789 Lakeshore",
    stage: "Scheduled Intro call",
    assignedTo: "Raj",
    phone: "+1 (555) 787-8787",
    email: "michael.s@example.com",
    createdAt: "11/17/2025",
    unitDetails: "Apartment",
    numberOfUnits: 15,
    lastCallStatus: "Connected",
    nextFollowUp: "11/22/2025",
    ownerType: "type1",
  },
  {
    id: 30,
    name: "Emily Davis",
    userType: "Owner",
    property: "156 Fernwood",
    stage: "Scheduled Intro call",
    assignedTo: "Nora",
    phone: "+1 (555) 898-9898",
    email: "emily.d@example.com",
    createdAt: "11/19/2025",
    unitDetails: "Multi Family",
    numberOfUnits: 2,
    lastCallStatus: "Connected",
    nextFollowUp: "11/24/2025",
    ownerType: "type1",
  },

  // ==========================================
  // OWNER LEADS - Working (10 records)
  // ==========================================
  {
    id: 31,
    name: "Jonathan Wright",
    userType: "Owner",
    property: "333 Parkview",
    stage: "Working",
    assignedTo: "Nina",
    phone: "+1 (555) 909-1010",
    email: "jonathan.w@example.com",
    createdAt: "10/15/2025",
    unitDetails: "Multi Family",
    numberOfUnits: 8,
    lastCallStatus: "Connected",
    nextFollowUp: "10/22/2025",
    ownerType: "type1",
  },
  {
    id: 32,
    name: "Stephanie Clark",
    userType: "Owner",
    property: "567 Orchard Way",
    stage: "Working",
    assignedTo: "Raj",
    phone: "+1 (555) 010-2020",
    email: "stephanie.c@example.com",
    createdAt: "10/18/2025",
    unitDetails: "Single Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "10/25/2025",
    ownerType: "type1",
  },
  {
    id: 33,
    name: "David Wilson",
    userType: "Owner",
    property: "890 Cypress Ave",
    stage: "Working",
    assignedTo: "Kim",
    phone: "+1 (555) 111-3030",
    email: "david.w@example.com",
    createdAt: "10/20/2025",
    unitDetails: "Apartment",
    numberOfUnits: 24,
    lastCallStatus: "Connected",
    nextFollowUp: "10/27/2025",
    ownerType: "type1",
  },
  {
    id: 34,
    name: "Jennifer Lopez",
    userType: "Owner",
    property: "122 Walnut St",
    stage: "Working",
    assignedTo: "Luis",
    phone: "+1 (555) 212-4040",
    email: "jennifer.l@example.com",
    createdAt: "10/22/2025",
    unitDetails: "Multi Family",
    numberOfUnits: 4,
    lastCallStatus: "Connected",
    nextFollowUp: "10/29/2025",
    ownerType: "type1",
  },
  {
    id: 35,
    name: "Ryan Anderson",
    userType: "Owner",
    property: "455 Chestnut Blvd",
    stage: "Working",
    assignedTo: "Nora",
    phone: "+1 (555) 313-5050",
    email: "ryan.a@example.com",
    createdAt: "10/25/2025",
    unitDetails: "Single Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/01/2025",
    ownerType: "type1",
  },
  {
    id: 36,
    name: "Ashley Taylor",
    userType: "Owner",
    property: "678 Aspen Ct",
    stage: "Working",
    assignedTo: "Nina",
    phone: "+1 (555) 414-6060",
    email: "ashley.t@example.com",
    createdAt: "10/28/2025",
    unitDetails: "Multi Family",
    numberOfUnits: 6,
    lastCallStatus: "Connected",
    nextFollowUp: "11/04/2025",
    ownerType: "type1",
  },
  {
    id: 37,
    name: "Brandon Moore",
    userType: "Owner",
    property: "901 Dogwood Dr",
    stage: "Working",
    assignedTo: "Raj",
    phone: "+1 (555) 515-7070",
    email: "brandon.m@example.com",
    createdAt: "10/30/2025",
    unitDetails: "Apartment",
    numberOfUnits: 10,
    lastCallStatus: "Connected",
    nextFollowUp: "11/06/2025",
    ownerType: "type1",
  },
  {
    id: 38,
    name: "Amanda White",
    userType: "Owner",
    property: "234 Juniper Way",
    stage: "Working",
    assignedTo: "Kim",
    phone: "+1 (555) 616-8080",
    email: "amanda.w@example.com",
    createdAt: "11/02/2025",
    unitDetails: "Single Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/09/2025",
    ownerType: "type1",
  },
  {
    id: 39,
    name: "Justin Harris",
    userType: "Owner",
    property: "567 Poplar Lane",
    stage: "Working",
    assignedTo: "Luis",
    phone: "+1 (555) 717-9090",
    email: "justin.h@example.com",
    createdAt: "11/05/2025",
    unitDetails: "Multi Family",
    numberOfUnits: 3,
    lastCallStatus: "Connected",
    nextFollowUp: "11/12/2025",
    ownerType: "type1",
  },
  {
    id: 40,
    name: "Nicole Jackson",
    userType: "Owner",
    property: "890 Spruce Point",
    stage: "Working",
    assignedTo: "Nora",
    phone: "+1 (555) 818-0101",
    email: "nicole.j@example.com",
    createdAt: "11/08/2025",
    unitDetails: "Apartment",
    numberOfUnits: 16,
    lastCallStatus: "Connected",
    nextFollowUp: "11/15/2025",
    ownerType: "type1",
  },

  // ==========================================
  // OWNER LEADS - Closing (10 records)
  // ==========================================
  {
    id: 41,
    name: "Matthew Thomas",
    userType: "Owner",
    property: "123 Highland Ave",
    stage: "Closing",
    assignedTo: "Nina",
    phone: "+1 (555) 919-1212",
    email: "matthew.t@example.com",
    createdAt: "09/15/2025",
    unitDetails: "Multi Family",
    numberOfUnits: 12,
    lastCallStatus: "Connected",
    nextFollowUp: "09/20/2025",
    ownerType: "type1",
  },
  {
    id: 42,
    name: "Lauren Robinson",
    userType: "Owner",
    property: "456 Greenfield",
    stage: "Closing",
    assignedTo: "Raj",
    phone: "+1 (555) 020-2323",
    email: "lauren.r@example.com",
    createdAt: "09/18/2025",
    unitDetails: "Single Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "09/23/2025",
    ownerType: "type1",
  },
  {
    id: 43,
    name: "Joshua Walker",
    userType: "Owner",
    property: "789 Sunset Ridge",
    stage: "Closing",
    assignedTo: "Kim",
    phone: "+1 (555) 121-3434",
    email: "joshua.w@example.com",
    createdAt: "09/22/2025",
    unitDetails: "Apartment",
    numberOfUnits: 30,
    lastCallStatus: "Connected",
    nextFollowUp: "09/27/2025",
    ownerType: "type1",
  },
  {
    id: 44,
    name: "Megan Hall",
    userType: "Owner",
    property: "012 Bayside Dr",
    stage: "Closing",
    assignedTo: "Luis",
    phone: "+1 (555) 222-4545",
    email: "megan.h@example.com",
    createdAt: "09/25/2025",
    unitDetails: "Multi Family",
    numberOfUnits: 5,
    lastCallStatus: "Connected",
    nextFollowUp: "09/30/2025",
    ownerType: "type1",
  },
  {
    id: 45,
    name: "Tyler Young",
    userType: "Owner",
    property: "345 Mountain View",
    stage: "Closing",
    assignedTo: "Nora",
    phone: "+1 (555) 323-5656",
    email: "tyler.y@example.com",
    createdAt: "09/28/2025",
    unitDetails: "Single Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "10/03/2025",
    ownerType: "type1",
  },
  {
    id: 46,
    name: "Sarah King",
    userType: "Owner",
    property: "678 Valley Vista",
    stage: "Closing",
    assignedTo: "Nina",
    phone: "+1 (555) 424-6767",
    email: "sarah.k@example.com",
    createdAt: "10/01/2025",
    unitDetails: "Multi Family",
    numberOfUnits: 8,
    lastCallStatus: "Connected",
    nextFollowUp: "10/06/2025",
    ownerType: "type1",
  },
  {
    id: 47,
    name: "Jason Scott",
    userType: "Owner",
    property: "901 Canyon Rd",
    stage: "Closing",
    assignedTo: "Raj",
    phone: "+1 (555) 525-7878",
    email: "jason.s@example.com",
    createdAt: "10/04/2025",
    unitDetails: "Apartment",
    numberOfUnits: 18,
    lastCallStatus: "Connected",
    nextFollowUp: "10/09/2025",
    ownerType: "type1",
  },
  {
    id: 48,
    name: "Heather Green",
    userType: "Owner",
    property: "234 Forest Hill",
    stage: "Closing",
    assignedTo: "Kim",
    phone: "+1 (555) 626-8989",
    email: "heather.g@example.com",
    createdAt: "10/07/2025",
    unitDetails: "Single Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "10/12/2025",
    ownerType: "type1",
  },
  {
    id: 49,
    name: "Eric Adams",
    userType: "Owner",
    property: "567 Lakewood",
    stage: "Closing",
    assignedTo: "Luis",
    phone: "+1 (555) 727-9090",
    email: "eric.a@example.com",
    createdAt: "10/10/2025",
    unitDetails: "Multi Family",
    numberOfUnits: 4,
    lastCallStatus: "Connected",
    nextFollowUp: "10/15/2025",
    ownerType: "type1",
  },
  {
    id: 50,
    name: "Kimberly Baker",
    userType: "Owner",
    property: "890 Riverview",
    stage: "Closing",
    assignedTo: "Nora",
    phone: "+1 (555) 828-0101",
    email: "kimberly.b@example.com",
    createdAt: "10/13/2025",
    unitDetails: "Apartment",
    numberOfUnits: 22,
    lastCallStatus: "Connected",
    nextFollowUp: "10/18/2025",
    ownerType: "type1",
  },

  // ==========================================
  // OWNER LEADS - New client (10 records)
  // ==========================================
  {
    id: 51,
    name: "Richard Nelson",
    userType: "Owner",
    property: "123 Oakwood Estates",
    stage: "New client",
    assignedTo: "Nina",
    phone: "+1 (555) 929-1212",
    email: "richard.n@example.com",
    createdAt: "08/15/2025",
    unitDetails: "Multi Family",
    numberOfUnits: 15,
    lastCallStatus: "Connected",
    nextFollowUp: "08/20/2025",
    ownerType: "type1",
  },
  {
    id: 52,
    name: "Christina Carter",
    userType: "Owner",
    property: "456 Pine Manor",
    stage: "New client",
    assignedTo: "Raj",
    phone: "+1 (555) 030-2323",
    email: "christina.c@example.com",
    createdAt: "08/20/2025",
    unitDetails: "Single Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "08/25/2025",
    ownerType: "type1",
  },
  {
    id: 53,
    name: "Steven Mitchell",
    userType: "Owner",
    property: "789 Cedar Heights",
    stage: "New client",
    assignedTo: "Kim",
    phone: "+1 (555) 131-3434",
    email: "steven.m@example.com",
    createdAt: "08/25/2025",
    unitDetails: "Apartment",
    numberOfUnits: 40,
    lastCallStatus: "Connected",
    nextFollowUp: "08/30/2025",
    ownerType: "type1",
  },
  {
    id: 54,
    name: "Rebecca Perez",
    userType: "Owner",
    property: "012 Maple Gardens",
    stage: "New client",
    assignedTo: "Luis",
    phone: "+1 (555) 232-4545",
    email: "rebecca.p@example.com",
    createdAt: "09/01/2025",
    unitDetails: "Multi Family",
    numberOfUnits: 6,
    lastCallStatus: "Connected",
    nextFollowUp: "09/06/2025",
    ownerType: "type1",
  },
  {
    id: 55,
    name: "Patrick Roberts",
    userType: "Owner",
    property: "345 Birch Commons",
    stage: "New client",
    assignedTo: "Nora",
    phone: "+1 (555) 333-5656",
    email: "patrick.r@example.com",
    createdAt: "09/05/2025",
    unitDetails: "Single Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "09/10/2025",
    ownerType: "type1",
  },
  {
    id: 56,
    name: "Angela Turner",
    userType: "Owner",
    property: "678 Willow Park",
    stage: "New client",
    assignedTo: "Nina",
    phone: "+1 (555) 434-6767",
    email: "angela.t@example.com",
    createdAt: "09/08/2025",
    unitDetails: "Multi Family",
    numberOfUnits: 10,
    lastCallStatus: "Connected",
    nextFollowUp: "09/13/2025",
    ownerType: "type1",
  },
  {
    id: 57,
    name: "Gregory Phillips",
    userType: "Owner",
    property: "901 Elm Square",
    stage: "New client",
    assignedTo: "Raj",
    phone: "+1 (555) 535-7878",
    email: "gregory.p@example.com",
    createdAt: "09/10/2025",
    unitDetails: "Apartment",
    numberOfUnits: 25,
    lastCallStatus: "Connected",
    nextFollowUp: "09/15/2025",
    ownerType: "type1",
  },
  {
    id: 58,
    name: "Michelle Campbell",
    userType: "Owner",
    property: "234 Aspen Grove",
    stage: "New client",
    assignedTo: "Kim",
    phone: "+1 (555) 636-8989",
    email: "michelle.c@example.com",
    createdAt: "09/12/2025",
    unitDetails: "Single Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "09/17/2025",
    ownerType: "type1",
  },
  {
    id: 59,
    name: "Kenneth Parker",
    userType: "Owner",
    property: "567 Dogwood Plaza",
    stage: "New client",
    assignedTo: "Luis",
    phone: "+1 (555) 737-9090",
    email: "kenneth.p@example.com",
    createdAt: "09/14/2025",
    unitDetails: "Multi Family",
    numberOfUnits: 7,
    lastCallStatus: "Connected",
    nextFollowUp: "09/19/2025",
    ownerType: "type1",
  },
  {
    id: 60,
    name: "Donna Evans",
    userType: "Owner",
    property: "890 Cypress Pointe",
    stage: "New client",
    assignedTo: "Nora",
    phone: "+1 (555) 838-0101",
    email: "donna.e@example.com",
    createdAt: "09/16/2025",
    unitDetails: "Apartment",
    numberOfUnits: 35,
    lastCallStatus: "Connected",
    nextFollowUp: "09/21/2025",
    ownerType: "type1",
  },

  // ==========================================
  // TENANT LEADS - New Prospects (10 records)
  // ==========================================
  {
    id: 101,
    name: "John Smith",
    userType: "Tenant",
    property: "123 Main St",
    stage: "New Prospects",
    assignedTo: "Raj",
    phone: "+1 (555) 123-4567",
    email: "john.smith@example.com",
    createdAt: "11/15/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "No Answer",
    nextFollowUp: "11/20/2025",
  },
  {
    id: 102,
    name: "Alice Johnson",
    userType: "Tenant",
    property: "N/A",
    stage: "New Prospects",
    assignedTo: "Nina",
    phone: "+1 (555) 234-5678",
    email: "alice.j@example.com",
    createdAt: "11/18/2025",
    unitDetails: "Single Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/21/2025",
  },
  {
    id: 103,
    name: "Bob Williams",
    userType: "Tenant",
    property: "N/A",
    stage: "New Prospects",
    assignedTo: "Kim",
    phone: "+1 (555) 345-6789",
    email: "bob.w@example.com",
    createdAt: "11/19/2025",
    unitDetails: "Multi Family",
    numberOfUnits: 2,
    lastCallStatus: "Call me Later",
    nextFollowUp: "11/22/2025",
  },
  {
    id: 104,
    name: "Carol Davis",
    userType: "Tenant",
    property: "N/A",
    stage: "New Prospects",
    assignedTo: "Luis",
    phone: "+1 (555) 456-7890",
    email: "carol.d@example.com",
    createdAt: "11/20/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "No Answer",
    nextFollowUp: "11/23/2025",
  },
  {
    id: 105,
    name: "David Martinez",
    userType: "Tenant",
    property: "N/A",
    stage: "New Prospects",
    assignedTo: "Nora",
    phone: "+1 (555) 567-8901",
    email: "david.m@example.com",
    createdAt: "11/21/2025",
    unitDetails: "Single Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/24/2025",
  },
  {
    id: 106,
    name: "Eva Rodriguez",
    userType: "Tenant",
    property: "N/A",
    stage: "New Prospects",
    assignedTo: "Raj",
    phone: "+1 (555) 678-9012",
    email: "eva.r@example.com",
    createdAt: "11/22/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "No Answer",
    nextFollowUp: "11/25/2025",
  },
  {
    id: 107,
    name: "Frank Wilson",
    userType: "Tenant",
    property: "N/A",
    stage: "New Prospects",
    assignedTo: "Nina",
    phone: "+1 (555) 789-0123",
    email: "frank.w@example.com",
    createdAt: "11/23/2025",
    unitDetails: "Multi Family",
    numberOfUnits: 1,
    lastCallStatus: "Call me Later",
    nextFollowUp: "11/26/2025",
  },
  {
    id: 108,
    name: "Grace Lee",
    userType: "Tenant",
    property: "N/A",
    stage: "New Prospects",
    assignedTo: "Kim",
    phone: "+1 (555) 890-1234",
    email: "grace.l@example.com",
    createdAt: "11/24/2025",
    unitDetails: "Single Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/27/2025",
  },
  {
    id: 109,
    name: "Henry Brown",
    userType: "Tenant",
    property: "N/A",
    stage: "New Prospects",
    assignedTo: "Luis",
    phone: "+1 (555) 901-2345",
    email: "henry.b@example.com",
    createdAt: "11/25/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "No Answer",
    nextFollowUp: "11/28/2025",
  },
  {
    id: 110,
    name: "Ivy Chen",
    userType: "Tenant",
    property: "N/A",
    stage: "New Prospects",
    assignedTo: "Nora",
    phone: "+1 (555) 012-3456",
    email: "ivy.c@example.com",
    createdAt: "11/26/2025",
    unitDetails: "Multi Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/29/2025",
  },

  // ==========================================
  // TENANT LEADS - Appointment Booked with LC (10 records)
  // ==========================================
  {
    id: 111,
    name: "Charlie Brown",
    userType: "Tenant",
    property: "456 Oak Ave",
    stage: "Appointment Booked with LC",
    assignedTo: "Luis",
    phone: "+1 (555) 456-7890",
    email: "charlie.b@example.com",
    createdAt: "11/20/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "No Answer",
    nextFollowUp: "11/23/2025",
  },
  {
    id: 112,
    name: "Diana Prince",
    userType: "Tenant",
    property: "789 Elm St",
    stage: "Appointment Booked with LC",
    assignedTo: "Raj",
    phone: "+1 (555) 567-8901",
    email: "diana.p@example.com",
    createdAt: "11/21/2025",
    unitDetails: "Single Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/24/2025",
  },
  {
    id: 113,
    name: "Jack Thompson",
    userType: "Tenant",
    property: "321 Pine Rd",
    stage: "Appointment Booked with LC",
    assignedTo: "Nina",
    phone: "+1 (555) 111-2222",
    email: "jack.t@example.com",
    createdAt: "11/22/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/25/2025",
  },
  {
    id: 114,
    name: "Karen White",
    userType: "Tenant",
    property: "654 Maple Dr",
    stage: "Appointment Booked with LC",
    assignedTo: "Kim",
    phone: "+1 (555) 222-3333",
    email: "karen.w@example.com",
    createdAt: "11/23/2025",
    unitDetails: "Multi Family",
    numberOfUnits: 1,
    lastCallStatus: "No Answer",
    nextFollowUp: "11/26/2025",
  },
  {
    id: 115,
    name: "Leo Garcia",
    userType: "Tenant",
    property: "987 Cedar Ln",
    stage: "Appointment Booked with LC",
    assignedTo: "Luis",
    phone: "+1 (555) 333-4444",
    email: "leo.g@example.com",
    createdAt: "11/24/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "Call me Later",
    nextFollowUp: "11/27/2025",
  },
  {
    id: 116,
    name: "Mary Adams",
    userType: "Tenant",
    property: "147 Birch Ave",
    stage: "Appointment Booked with LC",
    assignedTo: "Nora",
    phone: "+1 (555) 444-5555",
    email: "mary.a@example.com",
    createdAt: "11/25/2025",
    unitDetails: "Single Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/28/2025",
  },
  {
    id: 117,
    name: "Nathan Scott",
    userType: "Tenant",
    property: "258 Walnut St",
    stage: "Appointment Booked with LC",
    assignedTo: "Raj",
    phone: "+1 (555) 555-6666",
    email: "nathan.s@example.com",
    createdAt: "11/26/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "No Answer",
    nextFollowUp: "11/29/2025",
  },
  {
    id: 118,
    name: "Olivia Turner",
    userType: "Tenant",
    property: "369 Cherry Blvd",
    stage: "Appointment Booked with LC",
    assignedTo: "Nina",
    phone: "+1 (555) 666-7777",
    email: "olivia.t@example.com",
    createdAt: "11/27/2025",
    unitDetails: "Multi Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/30/2025",
  },
  {
    id: 119,
    name: "Paul Harris",
    userType: "Tenant",
    property: "480 Spruce Ct",
    stage: "Appointment Booked with LC",
    assignedTo: "Kim",
    phone: "+1 (555) 777-8888",
    email: "paul.h@example.com",
    createdAt: "11/28/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "Call me Later",
    nextFollowUp: "12/01/2025",
  },
  {
    id: 120,
    name: "Quinn Moore",
    userType: "Tenant",
    property: "591 Ash Dr",
    stage: "Appointment Booked with LC",
    assignedTo: "Luis",
    phone: "+1 (555) 888-9999",
    email: "quinn.m@example.com",
    createdAt: "11/29/2025",
    unitDetails: "Single Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "12/02/2025",
  },

  // ==========================================
  // TENANT LEADS - Scheduled Showing (10 records)
  // ==========================================
  {
    id: 121,
    name: "Ivy Chen",
    userType: "tenant",
    property: "Single Family - 1 Unit",
    stage: "New Prospects",
    assignedTo: "George",
    phone: "555-0221",
    email: "ivy.chen@email.com",
    createdAt: "2025-11-29",
    unitDetails: "Single Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/29/2025",
    prospectType: "type1",
  },
  {
    id: 122,
    name: "Henry Brooks",
    userType: "tenant",
    property: "Apartment - 1 Unit",
    stage: "New Prospects",
    assignedTo: "George",
    phone: "555-0222",
    email: "henry.brooks@email.com",
    createdAt: "2025-11-28",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "No Answer",
    nextFollowUp: "11/28/2025",
    prospectType: "type1",
  },
  {
    id: 123,
    name: "Grace Lee",
    userType: "tenant",
    property: "Single Family - 1 Unit",
    stage: "New Prospects",
    assignedTo: "George",
    phone: "555-0223",
    email: "grace.lee@email.com",
    createdAt: "2025-12-01",
    unitDetails: "Single Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "12/01/2025",
    prospectType: "type1",
  },
  {
    id: 124,
    name: "Quinn Morrison",
    userType: "tenant",
    property: "Single Family - 1 Unit",
    stage: "Initial Inquiry",
    assignedTo: "George",
    phone: "555-0224",
    email: "quinn.morrison@email.com",
    createdAt: "2025-12-02",
    unitDetails: "Single Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "12/02/2025",
    prospectType: "type2", // Prospect type 2
  },
  {
    id: 125,
    name: "Paul Harper",
    userType: "tenant",
    property: "Apartment - 1 Unit",
    stage: "Initial Inquiry",
    assignedTo: "George",
    phone: "555-0225",
    email: "paul.harper@email.com",
    createdAt: "2025-12-01",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "Call me Later",
    nextFollowUp: "12/01/2025",
    prospectType: "type2",
  },
  {
    id: 126,
    name: "Olivia Turner",
    userType: "tenant",
    property: "Multi Family - 1 Unit",
    stage: "Initial Inquiry",
    assignedTo: "George",
    phone: "555-0226",
    email: "olivia.turner@email.com",
    createdAt: "2025-11/30",
    unitDetails: "Multi Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/30/2025",
    prospectType: "type2",
  },
  {
    id: 127,
    name: "Nathan Price",
    userType: "tenant",
    property: "Apartment - 1 Unit",
    stage: "Lead Received",
    assignedTo: "George",
    phone: "555-0227",
    email: "nathan.price@email.com",
    createdAt: "2025-12-03",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "12/03/2025",
    prospectType: "type3", // Prospect type 3
  },
  {
    id: 128,
    name: "Michelle Davis",
    userType: "tenant",
    property: "Single Family - 1 Unit",
    stage: "Lead Received",
    assignedTo: "George",
    phone: "555-0228",
    email: "michelle.davis@email.com",
    createdAt: "2025-12-02",
    unitDetails: "Single Family",
    numberOfUnits: 1,
    lastCallStatus: "No Answer",
    nextFollowUp: "12/02/2025",
    prospectType: "type3",
  },
  {
    id: 129,
    name: "Lucas Anderson",
    userType: "tenant",
    property: "Apartment - 1 Unit",
    stage: "Prospect Contacted",
    assignedTo: "George",
    phone: "555-0229",
    email: "lucas.anderson@email.com",
    createdAt: "2025-12-04",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "12/04/2025",
    prospectType: "type4", // Prospect type 4
  },
  {
    id: 130,
    name: "Karen Wilson",
    userType: "tenant",
    property: "Multi Family - 1 Unit",
    stage: "Prospect Contacted",
    assignedTo: "George",
    phone: "555-0230",
    email: "karen.wilson@email.com",
    createdAt: "2025-12-03",
    unitDetails: "Multi Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "12/03/2025",
    prospectType: "type4",
  },
  {
    id: 131,
    name: "Brian Kelly",
    userType: "Tenant",
    property: "111 First St",
    stage: "No Show – Prospect",
    assignedTo: "Raj",
    phone: "+1 (555) 101-0101",
    email: "brian.k@example.com",
    createdAt: "11/10/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "No Answer",
    nextFollowUp: "11/15/2025",
  },
  {
    id: 132,
    name: "Cindy Wright",
    userType: "Tenant",
    property: "222 Second Ave",
    stage: "No Show – Prospect",
    assignedTo: "Nina",
    phone: "+1 (555) 202-0202",
    email: "cindy.w@example.com",
    createdAt: "11/11/2025",
    unitDetails: "Single Family",
    numberOfUnits: 1,
    lastCallStatus: "No Answer",
    nextFollowUp: "11/16/2025",
  },
  {
    id: 133,
    name: "Derek Hall",
    userType: "Tenant",
    property: "333 Third Blvd",
    stage: "No Show – Prospect",
    assignedTo: "Kim",
    phone: "+1 (555) 303-0303",
    email: "derek.h@example.com",
    createdAt: "11/12/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "No Answer",
    nextFollowUp: "11/17/2025",
  },
  {
    id: 134,
    name: "Ellen Young",
    userType: "Tenant",
    property: "444 Fourth Dr",
    stage: "No Show – Prospect",
    assignedTo: "Luis",
    phone: "+1 (555) 404-0404",
    email: "ellen.y@example.com",
    createdAt: "11/13/2025",
    unitDetails: "Multi Family",
    numberOfUnits: 1,
    lastCallStatus: "Call me Later",
    nextFollowUp: "11/18/2025",
  },
  {
    id: 135,
    name: "Fred Baker",
    userType: "Tenant",
    property: "555 Fifth Ln",
    stage: "No Show – Prospect",
    assignedTo: "Nora",
    phone: "+1 (555) 505-0505",
    email: "fred.b@example.com",
    createdAt: "11/14/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "No Answer",
    nextFollowUp: "11/19/2025",
  },
  {
    id: 136,
    name: "Gloria Sanchez",
    userType: "Tenant",
    property: "666 Sixth Ct",
    stage: "No Show – Prospect",
    assignedTo: "Raj",
    phone: "+1 (555) 606-0606",
    email: "gloria.s@example.com",
    createdAt: "11/15/2025",
    unitDetails: "Single Family",
    numberOfUnits: 1,
    lastCallStatus: "No Answer",
    nextFollowUp: "11/20/2025",
  },
  {
    id: 137,
    name: "Howard Price",
    userType: "Tenant",
    property: "777 Seventh Way",
    stage: "No Show – Prospect",
    assignedTo: "Nina",
    phone: "+1 (555) 707-0707",
    email: "howard.p@example.com",
    createdAt: "11/16/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "No Answer",
    nextFollowUp: "11/21/2025",
  },
  {
    id: 138,
    name: "Irene Collins",
    userType: "Tenant",
    property: "888 Eighth Pl",
    stage: "No Show – Prospect",
    assignedTo: "Kim",
    phone: "+1 (555) 808-0808",
    email: "irene.c@example.com",
    createdAt: "11/17/2025",
    unitDetails: "Multi Family",
    numberOfUnits: 1,
    lastCallStatus: "Call me Later",
    nextFollowUp: "11/22/2025",
  },
  {
    id: 139,
    name: "James Reed",
    userType: "Tenant",
    property: "999 Ninth Rd",
    stage: "No Show – Prospect",
    assignedTo: "Luis",
    phone: "+1 (555) 909-0909",
    email: "james.r@example.com",
    createdAt: "11/18/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "No Answer",
    nextFollowUp: "11/23/2025",
  },
  {
    id: 140,
    name: "Kelly Morgan",
    userType: "Tenant",
    property: "100 Tenth St",
    stage: "No Show – Prospect",
    assignedTo: "Nora",
    phone: "+1 (555) 010-1010",
    email: "kelly.m@example.com",
    createdAt: "11/19/2025",
    unitDetails: "Single Family",
    numberOfUnits: 1,
    lastCallStatus: "No Answer",
    nextFollowUp: "11/24/2025",
  },

  // ==========================================
  // TENANT LEADS - Showing Agent – No Show (10 records)
  // ==========================================
  {
    id: 141,
    name: "Larry Cooper",
    userType: "Tenant",
    property: "112 Agent Way",
    stage: "Showing Agent – No Show",
    assignedTo: "Raj",
    phone: "+1 (555) 121-1212",
    email: "larry.c@example.com",
    createdAt: "11/08/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/12/2025",
  },
  {
    id: 142,
    name: "Monica Bell",
    userType: "Tenant",
    property: "223 Agent Ave",
    stage: "Showing Agent – No Show",
    assignedTo: "Nina",
    phone: "+1 (555) 232-2323",
    email: "monica.b@example.com",
    createdAt: "11/09/2025",
    unitDetails: "Single Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/13/2025",
  },
  {
    id: 143,
    name: "Nick Peterson",
    userType: "Tenant",
    property: "334 Agent Blvd",
    stage: "Showing Agent – No Show",
    assignedTo: "Kim",
    phone: "+1 (555) 343-3434",
    email: "nick.p@example.com",
    createdAt: "11/10/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/14/2025",
  },
  {
    id: 144,
    name: "Olivia Stone",
    userType: "Tenant",
    property: "445 Agent Dr",
    stage: "Showing Agent – No Show",
    assignedTo: "Luis",
    phone: "+1 (555) 454-4545",
    email: "olivia.s@example.com",
    createdAt: "11/11/2025",
    unitDetails: "Multi Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/15/2025",
  },
  {
    id: 145,
    name: "Peter Grant",
    userType: "Tenant",
    property: "556 Agent Ln",
    stage: "Showing Agent – No Show",
    assignedTo: "Nora",
    phone: "+1 (555) 565-5656",
    email: "peter.g@example.com",
    createdAt: "11/12/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/16/2025",
  },
  {
    id: 146,
    name: "Rita James",
    userType: "Tenant",
    property: "667 Agent Ct",
    stage: "Showing Agent – No Show",
    assignedTo: "Raj",
    phone: "+1 (555) 676-6767",
    email: "rita.j@example.com",
    createdAt: "11/13/2025",
    unitDetails: "Single Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/17/2025",
  },
  {
    id: 147,
    name: "Steve Howard",
    userType: "Tenant",
    property: "778 Agent Way",
    stage: "Showing Agent – No Show",
    assignedTo: "Nina",
    phone: "+1 (555) 787-7878",
    email: "steve.h@example.com",
    createdAt: "11/14/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/18/2025",
  },
  {
    id: 148,
    name: "Teresa Dixon",
    userType: "Tenant",
    property: "889 Agent Pl",
    stage: "Showing Agent – No Show",
    assignedTo: "Kim",
    phone: "+1 (555) 898-8989",
    email: "teresa.d@example.com",
    createdAt: "11/15/2025",
    unitDetails: "Multi Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/19/2025",
  },
  {
    id: 149,
    name: "Ulysses Ward",
    userType: "Tenant",
    property: "990 Agent Rd",
    stage: "Showing Agent – No Show",
    assignedTo: "Luis",
    phone: "+1 (555) 909-9090",
    email: "ulysses.w@example.com",
    createdAt: "11/16/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/20/2025",
  },
  {
    id: 150,
    name: "Vera Fox",
    userType: "Tenant",
    property: "101 Agent St",
    stage: "Showing Agent – No Show",
    assignedTo: "Nora",
    phone: "+1 (555) 010-0101",
    email: "vera.f@example.com",
    createdAt: "11/17/2025",
    unitDetails: "Single Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/21/2025",
  },

  // ==========================================
  // TENANT LEADS - Showing Completed – Awaiting Feedback (10 records)
  // ==========================================
  {
    id: 151,
    name: "Walter Burns",
    userType: "Tenant",
    property: "123 Feedback Ave",
    stage: "Showing Completed – Awaiting Feedback",
    assignedTo: "Raj",
    phone: "+1 (555) 131-1313",
    email: "walter.b@example.com",
    createdAt: "11/12/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/15/2025",
  },
  {
    id: 152,
    name: "Xena Ross",
    userType: "Tenant",
    property: "234 Feedback Blvd",
    stage: "Showing Completed – Awaiting Feedback",
    assignedTo: "Nina",
    phone: "+1 (555) 242-2424",
    email: "xena.r@example.com",
    createdAt: "11/13/2025",
    unitDetails: "Single Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/16/2025",
  },
  {
    id: 153,
    name: "York Sanders",
    userType: "Tenant",
    property: "345 Feedback Dr",
    stage: "Showing Completed – Awaiting Feedback",
    assignedTo: "Kim",
    phone: "+1 (555) 353-3535",
    email: "york.s@example.com",
    createdAt: "11/14/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/17/2025",
  },
  {
    id: 154,
    name: "Zara Mills",
    userType: "Tenant",
    property: "456 Feedback Ln",
    stage: "Showing Completed – Awaiting Feedback",
    assignedTo: "Luis",
    phone: "+1 (555) 464-4646",
    email: "zara.m@example.com",
    createdAt: "11/15/2025",
    unitDetails: "Multi Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/18/2025",
  },
  {
    id: 155,
    name: "Aaron Blake",
    userType: "Tenant",
    property: "567 Feedback Ct",
    stage: "Showing Completed – Awaiting Feedback",
    assignedTo: "Nora",
    phone: "+1 (555) 575-5757",
    email: "aaron.b@example.com",
    createdAt: "11/16/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/19/2025",
  },
  {
    id: 156,
    name: "Betty Cole",
    userType: "Tenant",
    property: "678 Feedback Way",
    stage: "Showing Completed – Awaiting Feedback",
    assignedTo: "Raj",
    phone: "+1 (555) 686-6868",
    email: "betty.c@example.com",
    createdAt: "11/17/2025",
    unitDetails: "Single Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/20/2025",
  },
  {
    id: 157,
    name: "Carl Dean",
    userType: "Tenant",
    property: "789 Feedback Pl",
    stage: "Showing Completed – Awaiting Feedback",
    assignedTo: "Nina",
    phone: "+1 (555) 797-7979",
    email: "carl.d@example.com",
    createdAt: "11/18/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/21/2025",
  },
  {
    id: 158,
    name: "Dana Ellis",
    userType: "Tenant",
    property: "890 Feedback Rd",
    stage: "Showing Completed – Awaiting Feedback",
    assignedTo: "Kim",
    phone: "+1 (555) 808-8080",
    email: "dana.e@example.com",
    createdAt: "11/19/2025",
    unitDetails: "Multi Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/22/2025",
  },
  {
    id: 159,
    name: "Earl Flynn",
    userType: "Tenant",
    property: "901 Feedback St",
    stage: "Showing Completed – Awaiting Feedback",
    assignedTo: "Luis",
    phone: "+1 (555) 919-9191",
    email: "earl.f@example.com",
    createdAt: "11/20/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/23/2025",
  },
  {
    id: 160,
    name: "Fiona Grant",
    userType: "Tenant",
    property: "012 Feedback Ave",
    stage: "Showing Completed – Awaiting Feedback",
    assignedTo: "Nora",
    phone: "+1 (555) 020-0202",
    email: "fiona.g@example.com",
    createdAt: "11/21/2025",
    unitDetails: "Single Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/24/2025",
  },

  // ==========================================
  // TENANT LEADS - Not Interested / Disliked Property (10 records)
  // ==========================================
  {
    id: 161,
    name: "George Hayes",
    userType: "Tenant",
    property: "111 Reject St",
    stage: "Not Interested / Disliked Property",
    assignedTo: "Raj",
    phone: "+1 (555) 141-1414",
    email: "george.h@example.com",
    createdAt: "11/05/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/10/2025",
  },
  {
    id: 162,
    name: "Helen Irwin",
    userType: "Tenant",
    property: "222 Reject Ave",
    stage: "Not Interested / Disliked Property",
    assignedTo: "Nina",
    phone: "+1 (555) 252-2525",
    email: "helen.i@example.com",
    createdAt: "11/06/2025",
    unitDetails: "Single Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/11/2025",
  },
  {
    id: 163,
    name: "Ivan Jones",
    userType: "Tenant",
    property: "333 Reject Blvd",
    stage: "Not Interested / Disliked Property",
    assignedTo: "Kim",
    phone: "+1 (555) 363-3636",
    email: "ivan.j@example.com",
    createdAt: "11/07/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/12/2025",
  },
  {
    id: 164,
    name: "Julia Kent",
    userType: "Tenant",
    property: "444 Reject Dr",
    stage: "Not Interested / Disliked Property",
    assignedTo: "Luis",
    phone: "+1 (555) 474-4747",
    email: "julia.k@example.com",
    createdAt: "11/08/2025",
    unitDetails: "Multi Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/13/2025",
  },
  {
    id: 165,
    name: "Kevin Lane",
    userType: "Tenant",
    property: "555 Reject Ln",
    stage: "Not Interested / Disliked Property",
    assignedTo: "Nora",
    phone: "+1 (555) 585-5858",
    email: "kevin.l@example.com",
    createdAt: "11/09/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/14/2025",
  },
  {
    id: 166,
    name: "Linda Mason",
    userType: "Tenant",
    property: "666 Reject Ct",
    stage: "Not Interested / Disliked Property",
    assignedTo: "Raj",
    phone: "+1 (555) 696-6969",
    email: "linda.m@example.com",
    createdAt: "11/10/2025",
    unitDetails: "Single Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/15/2025",
  },
  {
    id: 167,
    name: "Mark Nash",
    userType: "Tenant",
    property: "777 Reject Way",
    stage: "Not Interested / Disliked Property",
    assignedTo: "Nina",
    phone: "+1 (555) 707-7070",
    email: "mark.n@example.com",
    createdAt: "11/11/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/16/2025",
  },
  {
    id: 168,
    name: "Nancy Owen",
    userType: "Tenant",
    property: "888 Reject Pl",
    stage: "Not Interested / Disliked Property",
    assignedTo: "Kim",
    phone: "+1 (555) 818-8181",
    email: "nancy.o@example.com",
    createdAt: "11/12/2025",
    unitDetails: "Multi Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/17/2025",
  },
  {
    id: 169,
    name: "Oscar Perry",
    userType: "Tenant",
    property: "999 Reject Rd",
    stage: "Not Interested / Disliked Property",
    assignedTo: "Luis",
    phone: "+1 (555) 929-9292",
    email: "oscar.p@example.com",
    createdAt: "11/13/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/18/2025",
  },
  {
    id: 170,
    name: "Paula Quinn",
    userType: "Tenant",
    property: "100 Reject St",
    stage: "Not Interested / Disliked Property",
    assignedTo: "Nora",
    phone: "+1 (555) 030-0303",
    email: "paula.q@example.com",
    createdAt: "11/14/2025",
    unitDetails: "Single Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/19/2025",
  },

  // ==========================================
  // TENANT LEADS - Interested – Application Sent (10 records)
  // ==========================================
  {
    id: 171,
    name: "Quincy Roberts",
    userType: "Tenant",
    property: "123 Apply Ave",
    stage: "Interested – Application Sent",
    assignedTo: "Raj",
    phone: "+1 (555) 151-1515",
    email: "quincy.r@example.com",
    createdAt: "11/10/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/13/2025",
  },
  {
    id: 172,
    name: "Rose Stevens",
    userType: "Tenant",
    property: "234 Apply Blvd",
    stage: "Interested – Application Sent",
    assignedTo: "Nina",
    phone: "+1 (555) 262-2626",
    email: "rose.s@example.com",
    createdAt: "11/11/2025",
    unitDetails: "Single Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/14/2025",
  },
  {
    id: 173,
    name: "Scott Turner",
    userType: "Tenant",
    property: "345 Apply Dr",
    stage: "Interested – Application Sent",
    assignedTo: "Kim",
    phone: "+1 (555) 373-3737",
    email: "scott.t@example.com",
    createdAt: "11/12/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/15/2025",
  },
  {
    id: 174,
    name: "Tracy Underwood",
    userType: "Tenant",
    property: "456 Apply Ln",
    stage: "Interested – Application Sent",
    assignedTo: "Luis",
    phone: "+1 (555) 484-4848",
    email: "tracy.u@example.com",
    createdAt: "11/13/2025",
    unitDetails: "Multi Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/16/2025",
  },
  {
    id: 175,
    name: "Ursula Vance",
    userType: "Tenant",
    property: "567 Apply Ct",
    stage: "Interested – Application Sent",
    assignedTo: "Nora",
    phone: "+1 (555) 595-5959",
    email: "ursula.v@example.com",
    createdAt: "11/14/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/17/2025",
  },
  {
    id: 176,
    name: "Victor Walsh",
    userType: "Tenant",
    property: "678 Apply Way",
    stage: "Interested – Application Sent",
    assignedTo: "Raj",
    phone: "+1 (555) 606-6060",
    email: "victor.w@example.com",
    createdAt: "11/15/2025",
    unitDetails: "Single Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/18/2025",
  },
  {
    id: 177,
    name: "Wendy Xavier",
    userType: "Tenant",
    property: "789 Apply Pl",
    stage: "Interested – Application Sent",
    assignedTo: "Nina",
    phone: "+1 (555) 717-7171",
    email: "wendy.x@example.com",
    createdAt: "11/16/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/19/2025",
  },
  {
    id: 178,
    name: "Xander Young",
    userType: "Tenant",
    property: "890 Apply Rd",
    stage: "Interested – Application Sent",
    assignedTo: "Kim",
    phone: "+1 (555) 828-8282",
    email: "xander.y@example.com",
    createdAt: "11/17/2025",
    unitDetails: "Multi Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/20/2025",
  },
  {
    id: 179,
    name: "Yvonne Zimmer",
    userType: "Tenant",
    property: "901 Apply St",
    stage: "Interested – Application Sent",
    assignedTo: "Luis",
    phone: "+1 (555) 939-9393",
    email: "yvonne.z@example.com",
    createdAt: "11/18/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/21/2025",
  },
  {
    id: 180,
    name: "Zack Adams",
    userType: "Tenant",
    property: "012 Apply Ave",
    stage: "Interested – Application Sent",
    assignedTo: "Nora",
    phone: "+1 (555) 040-0404",
    email: "zack.a@example.com",
    createdAt: "11/19/2025",
    unitDetails: "Single Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/22/2025",
  },

  // ==========================================
  // TENANT LEADS - Application Received – Under Review (10 records)
  // ==========================================
  {
    id: 181,
    name: "Adam Brown",
    userType: "Tenant",
    property: "123 Review St",
    stage: "Application Received – Under Review",
    assignedTo: "Raj",
    phone: "+1 (555) 161-1616",
    email: "adam.b@example.com",
    createdAt: "11/08/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/11/2025",
  },
  {
    id: 182,
    name: "Beth Clark",
    userType: "Tenant",
    property: "234 Review Ave",
    stage: "Application Received – Under Review",
    assignedTo: "Nina",
    phone: "+1 (555) 272-2727",
    email: "beth.c@example.com",
    createdAt: "11/09/2025",
    unitDetails: "Single Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/12/2025",
  },
  {
    id: 183,
    name: "Chris Davis",
    userType: "Tenant",
    property: "345 Review Blvd",
    stage: "Application Received – Under Review",
    assignedTo: "Kim",
    phone: "+1 (555) 383-3838",
    email: "chris.d@example.com",
    createdAt: "11/10/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/13/2025",
  },
  {
    id: 184,
    name: "Diana Evans",
    userType: "Tenant",
    property: "456 Review Dr",
    stage: "Application Received – Under Review",
    assignedTo: "Luis",
    phone: "+1 (555) 494-4949",
    email: "diana.e@example.com",
    createdAt: "11/11/2025",
    unitDetails: "Multi Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/14/2025",
  },
  {
    id: 185,
    name: "Eric Ford",
    userType: "Tenant",
    property: "567 Review Ln",
    stage: "Application Received – Under Review",
    assignedTo: "Nora",
    phone: "+1 (555) 505-0505",
    email: "eric.f@example.com",
    createdAt: "11/12/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/15/2025",
  },
  {
    id: 186,
    name: "Fiona Green",
    userType: "Tenant",
    property: "678 Review Ct",
    stage: "Application Received – Under Review",
    assignedTo: "Raj",
    phone: "+1 (555) 616-6161",
    email: "fiona.green@example.com",
    createdAt: "11/13/2025",
    unitDetails: "Single Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/16/2025",
  },
  {
    id: 187,
    name: "Gary Hill",
    userType: "Tenant",
    property: "789 Review Way",
    stage: "Application Received – Under Review",
    assignedTo: "Nina",
    phone: "+1 (555) 727-7272",
    email: "gary.h@example.com",
    createdAt: "11/14/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/17/2025",
  },
  {
    id: 188,
    name: "Holly Irving",
    userType: "Tenant",
    property: "890 Review Pl",
    stage: "Application Received – Under Review",
    assignedTo: "Kim",
    phone: "+1 (555) 838-8383",
    email: "holly.i@example.com",
    createdAt: "11/15/2025",
    unitDetails: "Multi Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/18/2025",
  },
  {
    id: 189,
    name: "Ian James",
    userType: "Tenant",
    property: "901 Review Rd",
    stage: "Application Received – Under Review",
    assignedTo: "Luis",
    phone: "+1 (555) 949-9494",
    email: "ian.j@example.com",
    createdAt: "11/16/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/19/2025",
  },
  {
    id: 190,
    name: "Jill Kent",
    userType: "Tenant",
    property: "012 Review St",
    stage: "Application Received – Under Review",
    assignedTo: "Nora",
    phone: "+1 (555) 050-0505",
    email: "jill.k@example.com",
    createdAt: "11/17/2025",
    unitDetails: "Single Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/20/2025",
  },

  // ==========================================
  // TENANT LEADS - Application Rejected (10 records)
  // ==========================================
  {
    id: 191,
    name: "Kyle Lane",
    userType: "Tenant",
    property: "111 Denied St",
    stage: "Application Rejected",
    assignedTo: "Raj",
    phone: "+1 (555) 171-1717",
    email: "kyle.l@example.com",
    createdAt: "10/20/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "10/25/2025",
  },
  {
    id: 192,
    name: "Lisa Mason",
    userType: "Tenant",
    property: "222 Denied Ave",
    stage: "Application Rejected",
    assignedTo: "Nina",
    phone: "+1 (555) 282-2828",
    email: "lisa.m@example.com",
    createdAt: "10/22/2025",
    unitDetails: "Single Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "10/27/2025",
  },
  {
    id: 193,
    name: "Mike Nash",
    userType: "Tenant",
    property: "333 Denied Blvd",
    stage: "Application Rejected",
    assignedTo: "Kim",
    phone: "+1 (555) 393-3939",
    email: "mike.n@example.com",
    createdAt: "10/24/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "10/29/2025",
  },
  {
    id: 194,
    name: "Nina Owen",
    userType: "Tenant",
    property: "444 Denied Dr",
    stage: "Application Rejected",
    assignedTo: "Luis",
    phone: "+1 (555) 404-4040",
    email: "nina.o@example.com",
    createdAt: "10/26/2025",
    unitDetails: "Multi Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "10/31/2025",
  },
  {
    id: 195,
    name: "Oscar Perry",
    userType: "Tenant",
    property: "555 Denied Ln",
    stage: "Application Rejected",
    assignedTo: "Nora",
    phone: "+1 (555) 515-5151",
    email: "oscar.perry@example.com",
    createdAt: "10/28/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/02/2025",
  },
  {
    id: 196,
    name: "Pam Quinn",
    userType: "Tenant",
    property: "666 Denied Ct",
    stage: "Application Rejected",
    assignedTo: "Raj",
    phone: "+1 (555) 626-6262",
    email: "pam.q@example.com",
    createdAt: "10/30/2025",
    unitDetails: "Single Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/04/2025",
  },
  {
    id: 197,
    name: "Quinn Ross",
    userType: "Tenant",
    property: "777 Denied Way",
    stage: "Application Rejected",
    assignedTo: "Nina",
    phone: "+1 (555) 737-7373",
    email: "quinn.r@example.com",
    createdAt: "11/01/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/06/2025",
  },
  {
    id: 198,
    name: "Rita Stone",
    userType: "Tenant",
    property: "888 Denied Pl",
    stage: "Application Rejected",
    assignedTo: "Kim",
    phone: "+1 (555) 848-8484",
    email: "rita.s@example.com",
    createdAt: "11/03/2025",
    unitDetails: "Multi Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/08/2025",
  },
  {
    id: 199,
    name: "Sam Turner",
    userType: "Tenant",
    property: "999 Denied Rd",
    stage: "Application Rejected",
    assignedTo: "Luis",
    phone: "+1 (555) 959-9595",
    email: "sam.t@example.com",
    createdAt: "11/05/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/10/2025",
  },
  {
    id: 200,
    name: "Tara Underwood",
    userType: "Tenant",
    property: "100 Denied St",
    stage: "Application Rejected",
    assignedTo: "Nora",
    phone: "+1 (555) 060-0606",
    email: "tara.u@example.com",
    createdAt: "11/07/2025",
    unitDetails: "Single Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/12/2025",
  },

  // ==========================================
  // TENANT LEADS - Application Approved – Lease Sent (10 records)
  // ==========================================
  {
    id: 201,
    name: "Uma Vance",
    userType: "Tenant",
    property: "123 Approved St",
    stage: "Application Approved – Lease Sent",
    assignedTo: "Raj",
    phone: "+1 (555) 181-1818",
    email: "uma.v@example.com",
    createdAt: "11/01/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/04/2025",
  },
  {
    id: 202,
    name: "Vince Walsh",
    userType: "Tenant",
    property: "234 Approved Ave",
    stage: "Application Approved – Lease Sent",
    assignedTo: "Nina",
    phone: "+1 (555) 292-2929",
    email: "vince.w@example.com",
    createdAt: "11/02/2025",
    unitDetails: "Single Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/05/2025",
  },
  {
    id: 203,
    name: "Wendy Xavier",
    userType: "Tenant",
    property: "345 Approved Blvd",
    stage: "Application Approved – Lease Sent",
    assignedTo: "Kim",
    phone: "+1 (555) 303-3030",
    email: "wendy.xavier@example.com",
    createdAt: "11/03/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/06/2025",
  },
  {
    id: 204,
    name: "Xander York",
    userType: "Tenant",
    property: "456 Approved Dr",
    stage: "Application Approved – Lease Sent",
    assignedTo: "Luis",
    phone: "+1 (555) 414-4141",
    email: "xander.y@example.com",
    createdAt: "11/04/2025",
    unitDetails: "Multi Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/07/2025",
  },
  {
    id: 205,
    name: "Yolanda Zimmer",
    userType: "Tenant",
    property: "567 Approved Ln",
    stage: "Application Approved – Lease Sent",
    assignedTo: "Nora",
    phone: "+1 (555) 525-5252",
    email: "yolanda.z@example.com",
    createdAt: "11/05/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/08/2025",
  },
  {
    id: 206,
    name: "Zoe Adams",
    userType: "Tenant",
    property: "678 Approved Ct",
    stage: "Application Approved – Lease Sent",
    assignedTo: "Raj",
    phone: "+1 (555) 636-6363",
    email: "zoe.a@example.com",
    createdAt: "11/06/2025",
    unitDetails: "Single Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/09/2025",
  },
  {
    id: 207,
    name: "Alan Brown",
    userType: "Tenant",
    property: "789 Approved Way",
    stage: "Application Approved – Lease Sent",
    assignedTo: "Nina",
    phone: "+1 (555) 747-7474",
    email: "alan.b@example.com",
    createdAt: "11/07/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/10/2025",
  },
  {
    id: 208,
    name: "Bella Clark",
    userType: "Tenant",
    property: "890 Approved Pl",
    stage: "Application Approved – Lease Sent",
    assignedTo: "Kim",
    phone: "+1 (555) 858-8585",
    email: "bella.c@example.com",
    createdAt: "11/08/2025",
    unitDetails: "Multi Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/11/2025",
  },
  {
    id: 209,
    name: "Carl Davis",
    userType: "Tenant",
    property: "901 Approved Rd",
    stage: "Application Approved – Lease Sent",
    assignedTo: "Luis",
    phone: "+1 (555) 969-9696",
    email: "carl.davis@example.com",
    createdAt: "11/09/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/12/2025",
  },
  {
    id: 210,
    name: "Daisy Evans",
    userType: "Tenant",
    property: "012 Approved St",
    stage: "Application Approved – Lease Sent",
    assignedTo: "Nora",
    phone: "+1 (555) 070-0707",
    email: "daisy.e@example.com",
    createdAt: "11/10/2025",
    unitDetails: "Single Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/13/2025",
  },

  // ==========================================
  // TENANT LEADS - Lease Signed – Schedule Move In (10 records)
  // ==========================================
  {
    id: 211,
    name: "Ethan Ford",
    userType: "Tenant",
    property: "123 Signed St",
    stage: "Lease Signed – Schedule Move In",
    assignedTo: "Raj",
    phone: "+1 (555) 191-1919",
    email: "ethan.f@example.com",
    createdAt: "10/25/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "10/28/2025",
  },
  {
    id: 212,
    name: "Fay Green",
    userType: "Tenant",
    property: "234 Signed Ave",
    stage: "Lease Signed – Schedule Move In",
    assignedTo: "Nina",
    phone: "+1 (555) 202-2020",
    email: "fay.g@example.com",
    createdAt: "10/26/2025",
    unitDetails: "Single Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "10/29/2025",
  },
  {
    id: 213,
    name: "Greg Hill",
    userType: "Tenant",
    property: "345 Signed Blvd",
    stage: "Lease Signed – Schedule Move In",
    assignedTo: "Kim",
    phone: "+1 (555) 313-3131",
    email: "greg.h@example.com",
    createdAt: "10/27/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "10/30/2025",
  },
  {
    id: 214,
    name: "Hope Irving",
    userType: "Tenant",
    property: "456 Signed Dr",
    stage: "Lease Signed – Schedule Move In",
    assignedTo: "Luis",
    phone: "+1 (555) 424-4242",
    email: "hope.i@example.com",
    createdAt: "10/28/2025",
    unitDetails: "Multi Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "10/31/2025",
  },
  {
    id: 215,
    name: "Ivan James",
    userType: "Tenant",
    property: "567 Signed Ln",
    stage: "Lease Signed – Schedule Move In",
    assignedTo: "Nora",
    phone: "+1 (555) 535-5353",
    email: "ivan.james@example.com",
    createdAt: "10/29/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/01/2025",
  },
  {
    id: 216,
    name: "Jane Kent",
    userType: "Tenant",
    property: "678 Signed Ct",
    stage: "Lease Signed – Schedule Move In",
    assignedTo: "Raj",
    phone: "+1 (555) 646-6464",
    email: "jane.k@example.com",
    createdAt: "10/30/2025",
    unitDetails: "Single Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/02/2025",
  },
  {
    id: 217,
    name: "Kurt Lane",
    userType: "Tenant",
    property: "789 Signed Way",
    stage: "Lease Signed – Schedule Move In",
    assignedTo: "Nina",
    phone: "+1 (555) 757-7575",
    email: "kurt.l@example.com",
    createdAt: "10/31/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/03/2025",
  },
  {
    id: 218,
    name: "Lily Mason",
    userType: "Tenant",
    property: "890 Signed Pl",
    stage: "Lease Signed – Schedule Move In",
    assignedTo: "Kim",
    phone: "+1 (555) 868-8686",
    email: "lily.m@example.com",
    createdAt: "11/01/2025",
    unitDetails: "Multi Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/04/2025",
  },
  {
    id: 219,
    name: "Mark Nash",
    userType: "Tenant",
    property: "901 Signed Rd",
    stage: "Lease Signed – Schedule Move In",
    assignedTo: "Luis",
    phone: "+1 (555) 979-9797",
    email: "mark.nash@example.com",
    createdAt: "11/02/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/05/2025",
  },
  {
    id: 220,
    name: "Nadia Owen",
    userType: "Tenant",
    property: "012 Signed St",
    stage: "Lease Signed – Schedule Move In",
    assignedTo: "Nora",
    phone: "+1 (555) 080-0808",
    email: "nadia.o@example.com",
    createdAt: "11/03/2025",
    unitDetails: "Single Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/06/2025",
  },

  // ==========================================
  // TENANT LEADS - Move In – Completed and Feedback (10 records)
  // ==========================================
  {
    id: 221,
    name: "Oliver Perry",
    userType: "Tenant",
    property: "123 Complete St",
    stage: "Move In – Completed and Feedback",
    assignedTo: "Raj",
    phone: "+1 (555) 101-2020",
    email: "oliver.p@example.com",
    createdAt: "10/01/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "10/15/2025",
  },
  {
    id: 222,
    name: "Penny Quinn",
    userType: "Tenant",
    property: "234 Complete Ave",
    stage: "Move In – Completed and Feedback",
    assignedTo: "Nina",
    phone: "+1 (555) 212-3030",
    email: "penny.q@example.com",
    createdAt: "10/03/2025",
    unitDetails: "Single Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "10/17/2025",
  },
  {
    id: 223,
    name: "Quinn Ross",
    userType: "Tenant",
    property: "345 Complete Blvd",
    stage: "Move In – Completed and Feedback",
    assignedTo: "Kim",
    phone: "+1 (555) 323-4040",
    email: "quinn.ross@example.com",
    createdAt: "10/05/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "10/19/2025",
  },
  {
    id: 224,
    name: "Rose Stone",
    userType: "Tenant",
    property: "456 Complete Dr",
    stage: "Move In – Completed and Feedback",
    assignedTo: "Luis",
    phone: "+1 (555) 434-5050",
    email: "rose.s@example.com",
    createdAt: "10/07/2025",
    unitDetails: "Multi Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "10/21/2025",
  },
  {
    id: 225,
    name: "Steve Turner",
    userType: "Tenant",
    property: "567 Complete Ln",
    stage: "Move In – Completed and Feedback",
    assignedTo: "Nora",
    phone: "+1 (555) 545-6060",
    email: "steve.t@example.com",
    createdAt: "10/09/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "10/23/2025",
  },
  {
    id: 226,
    name: "Tina Underwood",
    userType: "Tenant",
    property: "678 Complete Ct",
    stage: "Move In – Completed and Feedback",
    assignedTo: "Raj",
    phone: "+1 (555) 656-7070",
    email: "tina.u@example.com",
    createdAt: "10/11/2025",
    unitDetails: "Single Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "10/25/2025",
  },
  {
    id: 227,
    name: "Ulrich Vance",
    userType: "Tenant",
    property: "789 Complete Way",
    stage: "Move In – Completed and Feedback",
    assignedTo: "Nina",
    phone: "+1 (555) 767-8080",
    email: "ulrich.v@example.com",
    createdAt: "10/13/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "10/27/2025",
  },
  {
    id: 228,
    name: "Vera Walsh",
    userType: "Tenant",
    property: "890 Complete Pl",
    stage: "Move In – Completed and Feedback",
    assignedTo: "Kim",
    phone: "+1 (555) 878-9090",
    email: "vera.w@example.com",
    createdAt: "10/15/2025",
    unitDetails: "Multi Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "10/29/2025",
  },
  {
    id: 229,
    name: "Walter Xavier",
    userType: "Tenant",
    property: "901 Complete Rd",
    stage: "Move In – Completed and Feedback",
    assignedTo: "Luis",
    phone: "+1 (555) 989-0101",
    email: "walter.x@example.com",
    createdAt: "10/17/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "10/31/2025",
  },
  {
    id: 230,
    name: "Xena York",
    userType: "Tenant",
    property: "012 Complete St",
    stage: "Move In – Completed and Feedback",
    assignedTo: "Nora",
    phone: "+1 (555) 090-1212",
    email: "xena.y@example.com",
    createdAt: "10/19/2025",
    unitDetails: "Single Family",
    numberOfUnits: 1,
    lastCallStatus: "Connected",
    nextFollowUp: "11/02/2025",
  },

  // ==========================================
  // TENANT LEADS - Tenant – Lost or Backed Out (10 records)
  // ==========================================
  {
    id: 231,
    name: "Yale Zimmer",
    userType: "Tenant",
    property: "111 Lost St",
    stage: "Tenant – Lost or Backed Out",
    assignedTo: "Raj",
    phone: "+1 (555) 111-2323",
    email: "yale.z@example.com",
    createdAt: "09/15/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "No Answer",
    nextFollowUp: "09/20/2025",
  },
  {
    id: 232,
    name: "Zara Adams",
    userType: "Tenant",
    property: "222 Lost Ave",
    stage: "Tenant – Lost or Backed Out",
    assignedTo: "Nina",
    phone: "+1 (555) 222-3434",
    email: "zara.a@example.com",
    createdAt: "09/18/2025",
    unitDetails: "Single Family",
    numberOfUnits: 1,
    lastCallStatus: "Cancelled",
    nextFollowUp: "09/23/2025",
  },
  {
    id: 233,
    name: "Alex Brown",
    userType: "Tenant",
    property: "333 Lost Blvd",
    stage: "Tenant – Lost or Backed Out",
    assignedTo: "Kim",
    phone: "+1 (555) 333-4545",
    email: "alex.brown@example.com",
    createdAt: "09/20/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "No Answer",
    nextFollowUp: "09/25/2025",
  },
  {
    id: 234,
    name: "Bonnie Clark",
    userType: "Tenant",
    property: "444 Lost Dr",
    stage: "Tenant – Lost or Backed Out",
    assignedTo: "Luis",
    phone: "+1 (555) 444-5656",
    email: "bonnie.c@example.com",
    createdAt: "09/22/2025",
    unitDetails: "Multi Family",
    numberOfUnits: 1,
    lastCallStatus: "Cancelled",
    nextFollowUp: "09/27/2025",
  },
  {
    id: 235,
    name: "Chuck Davis",
    userType: "Tenant",
    property: "555 Lost Ln",
    stage: "Tenant – Lost or Backed Out",
    assignedTo: "Nora",
    phone: "+1 (555) 555-6767",
    email: "chuck.d@example.com",
    createdAt: "09/24/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "No Answer",
    nextFollowUp: "09/29/2025",
  },
  {
    id: 236,
    name: "Deb Evans",
    userType: "Tenant",
    property: "666 Lost Ct",
    stage: "Tenant – Lost or Backed Out",
    assignedTo: "Raj",
    phone: "+1 (555) 666-7878",
    email: "deb.e@example.com",
    createdAt: "09/26/2025",
    unitDetails: "Single Family",
    numberOfUnits: 1,
    lastCallStatus: "Cancelled",
    nextFollowUp: "10/01/2025",
  },
  {
    id: 237,
    name: "Ed Ford",
    userType: "Tenant",
    property: "777 Lost Way",
    stage: "Tenant – Lost or Backed Out",
    assignedTo: "Nina",
    phone: "+1 (555) 777-8989",
    email: "ed.f@example.com",
    createdAt: "09/28/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "No Answer",
    nextFollowUp: "10/03/2025",
  },
  {
    id: 238,
    name: "Faith Green",
    userType: "Tenant",
    property: "888 Lost Pl",
    stage: "Tenant – Lost or Backed Out",
    assignedTo: "Kim",
    phone: "+1 (555) 888-9090",
    email: "faith.g@example.com",
    createdAt: "09/30/2025",
    unitDetails: "Multi Family",
    numberOfUnits: 1,
    lastCallStatus: "Cancelled",
    nextFollowUp: "10/05/2025",
  },
  {
    id: 239,
    name: "Gus Hill",
    userType: "Tenant",
    property: "999 Lost Rd",
    stage: "Tenant – Lost or Backed Out",
    assignedTo: "Luis",
    phone: "+1 (555) 999-0101",
    email: "gus.h@example.com",
    createdAt: "10/02/2025",
    unitDetails: "Apartment",
    numberOfUnits: 1,
    lastCallStatus: "No Answer",
    nextFollowUp: "10/07/2025",
  },
  {
    id: 240,
    name: "Hannah Irving",
    userType: "Tenant",
    property: "100 Lost St",
    stage: "Tenant – Lost or Backed Out",
    assignedTo: "Nora",
    phone: "+1 (555) 100-1212",
    email: "hannah.i@example.com",
    createdAt: "10/04/2025",
    unitDetails: "Single Family",
    numberOfUnits: 1,
    lastCallStatus: "Cancelled",
    nextFollowUp: "10/09/2025",
  },
]

// Helper functions for stage styling
export function getStageCardStyle(stage: string): string {
  const stageColors: Record<string, string> = {
    // Owner Type 1 stages
    "New lead": "border-l-4 border-l-blue-500",
    "Attempting to contact": "border-l-4 border-l-amber-500",
    "Scheduled Intro call": "border-l-4 border-l-purple-500",
    Working: "border-l-4 border-l-teal-500",
    Closing: "border-l-4 border-l-emerald-500",
    "New client": "border-l-4 border-l-green-500",

    // Owner Type 2 stages
    "Initial Contact": "border-l-4 border-l-blue-500",
    Qualification: "border-l-4 border-l-amber-500",
    "Property Assessment": "border-l-4 border-l-purple-500",
    "Proposal Sent": "border-l-4 border-l-teal-500",
    Negotiation: "border-l-4 border-l-emerald-500",
    "Agreement Signed": "border-l-4 border-l-green-500",

    // Owner Type 3 stages
    "Inquiry Received": "border-l-4 border-l-blue-500",
    "Documentation Review": "border-l-4 border-l-amber-500",
    "Site Visit Scheduled": "border-l-4 border-l-purple-500",
    "Due Diligence": "border-l-4 border-l-teal-500",
    "Contract Phase": "border-l-4 border-l-emerald-500",
    Onboarded: "border-l-4 border-l-green-500",

    // Owner Type 4 stages
    "Lead Generation": "border-l-4 border-l-blue-500",
    "First Meeting": "border-l-4 border-l-amber-500",
    "Needs Analysis": "border-l-4 border-l-purple-500",
    "Solution Presentation": "border-l-4 border-l-teal-500",
    "Final Review": "border-l-4 border-l-emerald-500",
    "Client Active": "border-l-4 border-l-green-500",

    // Tenant stages
    "New Prospects": "border-l-4 border-l-blue-500",
    "Appointment Booked with LC": "border-l-4 border-l-indigo-500",
    "Scheduled Showing": "border-l-4 border-l-violet-500",
    "No Show – Prospect": "border-l-4 border-l-rose-500",
    "Showing Agent – No Show": "border-l-4 border-l-red-500",
    "Showing Completed – Awaiting Feedback": "border-l-4 border-l-amber-500",
    "Not Interested / Disliked Property": "border-l-4 border-l-gray-500",
    "Interested – Application Sent": "border-l-4 border-l-cyan-500",
    "Application Received – Under Review": "border-l-4 border-l-sky-500",
    "Application Rejected": "border-l-4 border-l-red-600",
    "Application Approved – Lease Sent": "border-l-4 border-l-emerald-500",
    "Lease Signed – Schedule Move In": "border-l-4 border-l-teal-500",
    "Move In – Completed and Feedback": "border-l-4 border-l-green-500",
    "Tenant – Lost or Backed Out": "border-l-4 border-l-gray-400",

    // Lease Prospect stages
    "Initial Inquiry": "border-l-4 border-l-blue-500",
    "Qualifying Call Scheduled": "border-l-4 border-l-indigo-500",
    "Property Tour Booked": "border-l-4 border-l-violet-500",
    "Tour Completed": "border-l-4 border-l-rose-500",
    "Application Submitted": "border-l-4 border-l-red-500",
    "Application Processing": "border-l-4 border-l-amber-500",
    "Approved – Lease Ready": "border-l-4 border-l-cyan-500",
    "Lead Received": "border-l-4 border-l-blue-500",
    "First Contact Made": "border-l-4 border-l-indigo-500",
    "Showing Requested": "border-l-4 border-l-violet-500",
    "Showing Confirmed": "border-l-4 border-l-rose-500",
    "Post-Showing Follow-up": "border-l-4 border-l-red-500",
    "Offer Submitted": "border-l-4 border-l-amber-500",
    "Lease Negotiation": "border-l-4 border-l-cyan-500",
    "Prospect Contacted": "border-l-4 border-l-blue-500",
    "Interest Confirmed": "border-l-4 border-l-indigo-500",
    "Viewing Scheduled": "border-l-4 border-l-violet-500",
    "Viewing Complete": "border-l-4 border-l-rose-500",
    "Decision Pending": "border-l-4 border-l-red-500",
    "Lease Documents Sent": "border-l-4 border-l-amber-500",
    "Move-in Scheduled": "border-l-4 border-l-cyan-500",
  }

  return stageColors[stage] || "border-l-4 border-l-gray-300"
}

export function getStageBadgeStyle(stage: string): string {
  // Consistent color system for lead statuses
  const stageStyles: Record<string, string> = {
    // New Lead stages - Green
    "New lead": "bg-emerald-500 text-white",
    "New Prospects": "bg-emerald-500 text-white",
    "Initial Contact": "bg-emerald-500 text-white",
    "Inquiry Received": "bg-emerald-500 text-white",
    "Lead Generation": "bg-emerald-500 text-white",
    "Lead Received": "bg-emerald-500 text-white",
    "Initial Inquiry": "bg-emerald-500 text-white",
    "Prospect Contacted": "bg-emerald-500 text-white",
    
    // Attempting to contact / Early stages - Amber/Orange
    "Attempting to contact": "bg-amber-500 text-white",
    "Appointment Booked with LC": "bg-amber-500 text-white",
    "Appointment Booked with LC": "bg-amber-500 text-white",
    "Qualification": "bg-amber-500 text-white",
    "Documentation Review": "bg-amber-500 text-white",
    "First Meeting": "bg-amber-500 text-white",
    "Qualifying Call Scheduled": "bg-amber-500 text-white",
    "First Contact Made": "bg-amber-500 text-white",
    "Interest Confirmed": "bg-amber-500 text-white",
    
    // Scheduled / In Progress stages - Blue
    "Scheduled Intro call": "bg-blue-500 text-white",
    "Scheduled Showing": "bg-blue-500 text-white",
    "Property Assessment": "bg-blue-500 text-white",
    "Site Visit Scheduled": "bg-blue-500 text-white",
    "Needs Analysis": "bg-blue-500 text-white",
    "Property Tour Booked": "bg-blue-500 text-white",
    "Tour Completed": "bg-blue-500 text-white",
    "Showing Requested": "bg-blue-500 text-white",
    "Showing Confirmed": "bg-blue-500 text-white",
    "Viewing Scheduled": "bg-blue-500 text-white",
    "Viewing Complete": "bg-blue-500 text-white",
    
    // Working / Active stages - Indigo
    "Working": "bg-indigo-500 text-white",
    "Showing Completed – Awaiting Feedback": "bg-indigo-500 text-white",
    "Proposal Sent": "bg-indigo-500 text-white",
    "Due Diligence": "bg-indigo-500 text-white",
    "Solution Presentation": "bg-indigo-500 text-white",
    "Application Submitted": "bg-indigo-500 text-white",
    "Application Processing": "bg-indigo-500 text-white",
    "Post-Showing Follow-up": "bg-indigo-500 text-white",
    "Decision Pending": "bg-indigo-500 text-white",
    
    // Closing stages - Purple
    "Closing": "bg-purple-500 text-white",
    "Interested – Application Sent": "bg-purple-500 text-white",
    "Application Received – Under Review": "bg-purple-500 text-white",
    "Application Approved – Lease Sent": "bg-purple-500 text-white",
    "Negotiation": "bg-purple-500 text-white",
    "Contract Phase": "bg-purple-500 text-white",
    "Final Review": "bg-purple-500 text-white",
    "Approved – Lease Ready": "bg-purple-500 text-white",
    "Offer Submitted": "bg-purple-500 text-white",
    "Lease Negotiation": "bg-purple-500 text-white",
    "Lease Documents Sent": "bg-purple-500 text-white",
    
    // Won / New Client stages - Teal
    "New client": "bg-teal-500 text-white",
    "Agreement Signed": "bg-teal-500 text-white",
    "Onboarded": "bg-teal-500 text-white",
    "Client Active": "bg-teal-500 text-white",
    "Lease Signed – Schedule Move In": "bg-teal-500 text-white",
    "Move In – Completed and Feedback": "bg-teal-500 text-white",
    "Move-in Scheduled": "bg-teal-500 text-white",
    
    // Lost / Rejected stages - Gray
    "No Show – Prospect": "bg-gray-400 text-gray-800",
    "Showing Agent – No Show": "bg-gray-400 text-gray-800",
    "Not Interested / Disliked Property": "bg-gray-400 text-gray-800",
    "Application Rejected": "bg-gray-400 text-gray-800",
    "Tenant – Lost or Backed Out": "bg-gray-400 text-gray-800",
  }
  
  return stageStyles[stage] || "bg-gray-100 text-gray-800"
}
