export { OwnerOverview } from "./Overview"
export { OwnerOverviewTasks, OwnerOverviewActivity, OwnerKPI } from "./Overview"
export type { OwnerOverviewActivitySummary } from "./Overview"
export { OwnerDetailsTab, type OwnerDetailsTabProps, type OwnerDetailsSectionConfig } from "./Details"
export { OwnerPropertyTab, type OwnerPropertyTabProps } from "./Property"
export { OwnerCommunicationTab, type OwnerCommunicationTabProps, type OwnerCommunicationTabContact } from "./Communication"
export { OwnerProcessesTab, type OwnerProcessesTabProps } from "./Processes"
export { OwnerDocumentTab, type OwnerDocumentTabProps } from "./Document"
export { OwnerAuditLogTab, type OwnerAuditLogTabProps } from "./AuditLog"
